name: 05 - Eventos en JavaScript - Tests

on:
  push:
    branches: [ main, practica-1-AdrianOlmedo]
    paths:
      - 'js/gestionPresupuestoWeb.js'
      - 'interaccionHTML.html'
      - 'test/05_**.cy.js'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Instalar dependencias del proyecto
        run: npm ci
      
      - name: Ejecutar tests
        run: npm run test5

